application: realtiger0982
version: 12
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

handlers:
#- url: /favicon.ico
#  static_files: apps/static/images/favicon.ico
#  upload: apps/static/images/favicon.ico
#
#- url: /robots.txt
#  static_files: apps/static/robots.txt
#  upload: apps/static/robots.txt

- url: /static
  static_dir: apps/static

- url: .*
  script: apps.app

libraries:
- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"

